# Generated by Django 2.2.3 on 2019-08-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190615_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
