# Generated by Django 2.2.3 on 2019-09-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190917_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
