# Generated by Django 2.1.1 on 2019-07-02 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_postreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreport',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostReport',
        ),
    ]
