# Generated by Django 2.1.1 on 2019-07-02 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_auto_20190702_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(choices=[('Nudity', 'Nudity'), ('Violence', 'Violence'), ('Harassment', 'Harassment'), ('Sucide or Self-Injury', 'Sucide or Self-Injury'), ('False News', 'False News'), ('Spam', 'Spam'), ('Unauthorized Sales', 'Unauthorized Sales'), ('Hate Speech', 'Hate Speech'), ('Terrosim', 'Terrosim')], max_length=30)),
                ('feedback_text', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
