# Generated by Django 2.1.1 on 2019-07-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_postreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
