# Generated by Django 2.1.1 on 2019-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20190708_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='feedback_text',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
